/*
Utility to convert a plain JSON list of questions into a seed module usable by the seeder.

Input format (JSON file) example:
[
  {
    "question": "What is Java?",
    "options": ["A", "B"],
    "answer": "A",
    "explanation": "...",
    "difficulty": "easy",
    "topic": "Basics"
  },
  ...
]

The script takes three command line args:
  node convertToSeedModule.js <input.json> <outputFileName> <subcategory>

`outputFileName` is the name of the `.js` module (without path) that will be placed
in the current directory (seedData). `subcategory` is the value used for every question's
subcategory field (e.g. "java", "python" etc.).

Once run it will write a file with the same structure as the existing seed modules,
which can then be imported by seed.js.
*/

const fs = require('fs');

function usage() {
  console.log('Usage: node convertToSeedModule.js <input.json> <outputFileName> <subcategory>');
  process.exit(1);
}

if (process.argv.length !== 5) usage();

const [,, inputPath, outputName, subcategory] = process.argv;

if (!fs.existsSync(inputPath)) {
  console.error('Input file not found:', inputPath);
  process.exit(1);
}

const raw = fs.readFileSync(inputPath, 'utf-8');
let questions;
try {
  questions = JSON.parse(raw);
} catch (err) {
  console.error('Error parsing JSON:', err.message);
  process.exit(1);
}

const seedArray = questions.map(q => {
  return {
    questionText: q.question || q.questionText || '',
    options: q.options || [],
    correctAnswer: q.answer || q.correctAnswer || '',
    explanation: q.explanation || '',
    difficulty: q.difficulty || 'medium',
    category: 'coding',
    subcategory,
    topic: q.topic || ''
  };
});

const outputPath = `./${outputName}`;
const fileContents = `// auto-generated by convertToSeedModule.js

const ${outputName.replace(/\.js$/, '')} = ${JSON.stringify(seedArray, null, 2)};

module.exports = ${outputName.replace(/\.js$/, '')};
`;

fs.writeFileSync(outputPath, fileContents);
console.log('Wrote', outputPath, 'with', seedArray.length, 'questions');
