// Seed data for Deloitte Interview Questions with Comprehensive Answers

const deloitteQuestions = [
  {
    question: "Explain Cybersecurity Frameworks?",
    answer: "Cybersecurity Frameworks provide structured approach to identify, protect, detect, respond to cyber threats. NIST CYBERSECURITY FRAMEWORK: (1) IDENTIFY - asset inventory, risks, (2) PROTECT - access controls, encryption, training, (3) DETECT - monitoring, threat detection, (4) RESPOND - incident response, containment, (5) RECOVER - restore operations, improve. Each function has categories and practices. ISO 27001: information security standard, 114 controls across 14 areas (asset management, access control, incident management, etc.). CIS Controls: 20 prioritized controls (access control, advanced malware protection, etc.). IMPACT/NISM: other frameworks with different approaches. SELECTION: depends on industry (banking prefers stricter), size, risk appetite. Large enterprises often multi-framework (NIST + ISO 27001). IMPLEMENTATION PHASES: (1) ASSESSMENT - current security posture, gaps against framework, (2) PLANNING - roadmap to compliance, (3) IMPLEMENTATION - controls deployment, (4) MONITORING - ongoing validation, (5) IMPROVEMENT - track, optimize. KEY CONCEPTS ACROSS FRAMEWORKS: asset management (know what you have), access control (least privilege), encryption (protect data), monitoring (detect threats), incident response (respond quickly), compliance (meet regulations). CHALLENGES: (1) COST - security investment significant, (2) COMPLEXITY - large organizations, (3) SKILLS - shortage of cybersecurity professionals, (4) CHANGE - threat landscape evolves, frameworks lag. GOVERNANCE: security committee, roles, policies, regular reviews. CIO/CISO responsibility. Understanding frameworks essential for security strategy, compliance, risk management in modern organizations.",
    category: "interview",
    subcategory: "deloitte",
    company: "Deloitte",
    topic: "Cybersecurity"
  },
  {
    question: "What is Risk Management in IT?",
    answer: "IT Risk Management identifies, analyzes, mitigates technology risks. RISK = LIKELIHOOD × IMPACT. Example: database failure very likely, high business impact, high risk. PROCESS: (1) IDENTIFICATION - list potential risks. Technical (system failure, data loss), operational (process failure), security (breaches), compliance (regulatory), strategic (market changes). (2) ANALYSIS - assess likelihood (probability 1-5), impact (severity 1-5), risk level. (3) MITIGATION - reduce risk via controls. Example: backup storage mitigates data loss risk. (4) MONITORING - track implemented controls, risk changes. (5) RESPONSE - when risk materializes, execute response plan. MITIGATION STRATEGIES: (1) AVOID - eliminate risk by not doing activity. Example: avoid outdated tech. (2) MITIGATE - reduce likelihood/impact via controls. (3) TRANSFER - shift risk to third party. Example: insurance, outsourcing. (4) ACCEPT - tolerate residual risk if mitigation cost higher than impact. RISK ASSESSMENT MATRIX: (1) IDENTIFY all risks, (2) RATE likelihood/impact, plot on matrix, (3) PRIORITIZE - high/high risks urgent, (4) TREAT - allocate resources accordingly. TYPES: (1) TECHNICAL - infrastructure failure, security vulnerabilities, (2) OPERATIONAL - human error, process failure, (3) SECURITY - cyberattacks, data theft, (4) COMPLIANCE - regulatory violations, (5) STRATEGIC - tech obsolescence, market changes, (6) REPUTATIONAL - customer loss from incidents. KEY METRICS: risk velocity (how fast materializing), blast radius (how many systems affected), recoverability (how long to recover). GOVERNANCE: risk management committee, CRO (Chief Risk Officer), enterprise risk management. Understanding IT risk management critical for business continuity, compliance, strategic decisions.",
    category: "interview",
    subcategory: "deloitte",
    company: "Deloitte",
    topic: "Risk Management"
  },
  {
    question: "Explain Audit and Compliance in IT?",
    answer: "IT Audit verifies IT controls effectiveness, assesses risk. IT Compliance ensures adherence to policies, regulations, standards. AUDIT OBJECTIVES: (1) TEST CONTROLS - verify controls functioning, (2) IDENTIFY RISKS - gaps, weaknesses, (3) RECOMMEND IMPROVEMENTS - strengthen controls, (4) ASSURANCE - management/board confidence, (5) COMPLIANCE VALIDATION - meet regulatory requirements. AUDIT PROCESS: (1) PLANNING - scope, risks, resources, (2) FIELDWORK - test controls, interviews, (3) DOCUMENTATION - evidence of audit, (4) REPORTING - findings, recommendations, (5) FOLLOW-UP - verify remediation. AUDIT TYPES: (1) FINANCIAL AUDIT - IT controls supporting financial reporting, (2) OPERATIONAL AUDIT - IT operational efficiency, (3) COMPLIANCE AUDIT - meet regulations, (4) SECURITY AUDIT - access controls, vulnerabilities, (5) SYSTEM AUDIT - application controls, integrity. COMPLIANCE FRAMEWORKS: (1) SOX (Sarbanes-Oxley) - financial controls for public companies, (2) HIPAA - healthcare data, (3) GDPR - EU data protection, (4) PCI DSS - payment card data, (5) NIST - cybersecurity, (6) ISO 27001 - information security. COMMON FINDINGS: (1) INADEQUATE SEGREGATION OF DUTIES - same person shouldn't create, approve, execute (fraud risk), (2) WEAK ACCESS CONTROLS - too many have excessive permissions, (3) INADEQUATE MONITORING - no detection of anomalies, (4) POOR CHANGE CONTROLS - unauthorized changes possible, (5) INADEQUATE DOCUMENTATION - hard to verify controls, (6) BACKUP/RECOVERY UNTESTED - disasters unmanageable. AUDITOR SKILLS: technical (systems), process (controls), risk, communication. SARBANES-OXLEY (SOX 404): management assesses internal controls, auditors attest. Significant IT compliance obligation for public companies. Understanding audit/compliance critical for governance, risk mitigation, regulatory readiness. Companies assign compliance roles, maintain evidence.",
    category: "interview",
    subcategory: "deloitte",
    company: "Deloitte",
    topic: "Compliance"
  },
  {
    question: "What is Organizational Transformation?",
    answer: "Organizational Transformation is significant structural, cultural, strategic change. Driven by external pressure (market, technology, competitors) or internal vision. DIMENSIONS: (1) STRUCTURAL - reporting lines, roles, teams reorganize. Example: shift from functional to matrix structure, cross-functional teams. (2) CULTURAL - mindset, values, behavior change. Example: from waterfall discipline to agile flexibility, risk-taking. (3) PROCESS - how work done, automation, efficiency. Example: manual approvals to automated workflows. (4) TECHNOLOGY - systems, infrastructure align with new model. (5) PEOPLE - skills, hiring, retention, development support new organization. STAGES: (1) AWARENESS - recognize need for change, (2) DESIRE - build commitment, overcome resistance, (3) KNOWLEDGE - train, communicate how to work differently, (4) ABILITY - practice, feedback, mastery, (5) REINFORCEMENT - systems, incentives maintain change. CHALLENGES: (1) RESISTANCE - humans resist change, fear unknown, (2) LEADERSHIP - transformational leadership needed, (3) COMMUNICATION - clear, consistent, frequent messaging, (4) RESOURCES - significant investment, (5) TIME - transformation 2-5 years typical, (6) MEASUREMENT - track progress, prove value. LEADERSHIP ROLES: (1) EXECUTIVE SPONSOR - senior leader drives, removes roadblocks, (2) CHANGE MANAGER - designs approach, communication, (3) PROJECT MANAGER - executes plan, (4) COACHES - support teams, (5) CHAMPIONS - early adopters, influence peers. RESISTANCE MANAGEMENT: (1) LISTEN - understand concerns, (2) COMMUNICATE - why change, benefits, (3) INVOLVE - include people in design, (4) TRAIN - build capabilities, (5) CELEBRATE - quick wins, progress recognition, (6) CONSEQUENCES - manage non-conformance. SUCCESS METRICS: adoption rates, productivity, employee engagement, financial impact. Organizational transformation critical in dynamic markets, Deloitte emphasizes change management consulting.",
    category: "interview",
    subcategory: "deloitte",
    company: "Deloitte",
    topic: "Organizational Change"
  },
  {
    question: "Explain IT Outsourcing and Offshoring?",
    answer: "OUTSOURCING: contracting IT functions to external vendor (could be onshore). Example: company outsources IT support to vendor. OFFSHORING: moving IT functions to offshore locations (usually lower cost countries like India, Philippines). MOTIVATIONS: (1) COST REDUCTION - offshore typically 30-50% cheaper, (2) FOCUS ON CORE BUSINESS - non-core functions to specialists, (3) ACCESS TO EXPERTISE - vendor specialized skills, (4) SCALABILITY - flex resources up/down, (5) GLOBAL REACH - 24/7 coverage via multiple locations. MODELS: (1) NEARSHORE - nearby country, shorter commute, easier time zone overlap. Example: Canadian company outsources to Mexican vendor. (2) OFFSHORE - distant country, maximum cost savings, communication challenges. (3) ONSHORE - within country, highest cost, minimal risks. FUNCTIONS OUTSOURCED: (1) IT SUPPORT - helpdesk, infrastructure management, (2) SOFTWARE DEVELOPMENT - coding, testing, (3) BUSINESS PROCESS OUTSOURCING (BPO) - data entry, transcription, (4) INFRASTRUCTURE - data center operations. RISKS: (1) QUALITY - vendor quality control, skill mismatches, (2) COMMUNICATION - language, time zone, cultural differences, (3) SECURITY - data in third-party hands, (4) LOSS OF CONTROL - less visibility, (5) VENDOR LOCK-IN - difficult to switch, (6) POLITICAL - visa restrictions, changing regulations. MITIGATION: (1) SLA (Service Level Agreement) - performance standards, penalties, (2) SECURITY AGREEMENT - data protection, compliance, (3) COMMUNICATION PLAN - regular sync, clear expectations, (4) KNOWLEDGE TRANSFER - documentation, training, (5) OFFBOARDING PLAN - exit strategy. SUCCESS FACTORS: clear requirements, vendor selection (reputation, capabilities), relationship management, monitoring. Trend: hybrid models (in-house critical, outsource routine). Deloitte advises on outsourcing strategy, vendor selection, governance.",
    category: "interview",
    subcategory: "deloitte",
    company: "Deloitte",
    topic: "IT Service Management"
  },
  {
    question: "What is Business Continuity Planning (BCP)?",
    answer: "Business Continuity Planning prepares organization to continue operations during disruptions (disasters, outages, incidents). GOAL: minimize downtime, data loss, revenue impact. BUSINESS IMPACT ANALYSIS (BIA): identifies critical business functions, acceptable downtime (RTO - Recovery Time Objective), maximum data loss (RPO - Recovery Point Objective). Example: payment processing RTO 1 hour (must recover within 1 hour), RPO 15 minutes (max 15 minutes of data loss acceptable). RTOs vary: critical (1 hour), important (4 hours), normal (24 hours). DISASTER RECOVERY PLAN (DRP): technical focus, how to recover systems, infrastructure. Steps: (1) IDENTIFY CRITICAL SYSTEMS, (2) BACKUP STRATEGIES (daily, incremental, offsite), (3) RECOVERY PROCEDURES, (4) RTO/RPO TARGETS, (5) TESTING. BUSINESS CONTINUITY PLAN (BCP): broader than DRP, includes people, processes, communication. Example: during data center failure, activate alternate facility, redirect operations, communicate with customers. PLAN COMPONENTS: (1) EXECUTIVE SUMMARY - high-level overview, (2) BUSINESS IMPACT ANALYSIS - critical functions, (3) RECOVERY PROCEDURES - step-by-step (activate alternate site, fail over systems, communicate), (4) ROLES & RESPONSIBILITIES - team structure, decision makers, (5) COMMUNICATION PLAN - notify employees, customers, regulators, (6) TESTING PROCEDURES - how often, what to test, (7) MAINTENANCE - keep plan current. RECOVERY STRATEGIES: (1) BACKUP SITE - hot (immediately available), warm (hours to activate), cold (days to activate), (2) CLOUD BACKUP - scalable, cost-effective, (3) REDUNDANCY - duplicated systems, automatic failover, (4) GEOGRAPHIC DISTRIBUTION - facilities spread across regions, mitigates location disasters. TESTING: (1) TABLETOP - discussion, walk-through, (2) SIMULATION - partial systems tested, (3) FULL-SCALE - complete recovery exercise, (4) FREQUENCY - annually at minimum. CHALLENGES: (1) COST - significant, unclear ROI, (2) COMPLEXITY - large organizations, (3) TESTING DIFFICULTY - disruptive, (4) BUSINESS CHANGE - plan becomes stale. REGULATORY: financial institutions, healthcare required to have BCP, tested regularly. Recent examples: cloud outages, ransomware hitting organizations lacking good BCP. Understanding BCP critical for operational resilience.",
    category: "interview",
    subcategory: "deloitte",
    company: "Deloitte",
    topic: "Business Continuity"
  },
  {
    question: "Explain Performance Management in IT?",
    answer: "IT Performance Management monitors, optimizes IT service delivery aligned with business objectives. METRICS: (1) AVAILABILITY - % of time service available (target 99.9% = 99.9% uptime), (2) RESPONSE TIME - how fast service responds, (3) THROUGHPUT - capacity, requests/sec, (4) ERROR RATE - % of failed requests, (5) EFFICIENCY - cost per transaction, (6) CUSTOMER SATISFACTION - surveys, NPS (Net Promoter Score). OBJECTIVES: (1) ALIGN - IT performance with business goals, (2) BASELINE - establish current performance norms, (3) SET TARGETS - realistic ambitious goals, (4) MONITOR - continuous measurement, (5) REPORT - transparent reporting to stakeholders, (6) IMPROVE - identify and fix issues. TOOLS: (1) APM (Application Performance Monitoring) - track application metrics, (2) NPM (Network Performance Monitoring) - network health, (3) DATABASES - query performance, (4) LOG ANALYSIS - error tracking, (5) DASHBOARDS - visualize KPIs. SLA (Service Level Agreements): contracts defining expected performance, consequences. Example: cloud provider agrees 99.99% availability, credit if lower. KPI (Key Performance Indicators): tied to business objectives. Example: reduce transaction processing time 30% (improves customer experience, reduces cost). BALANCED SCORECARD: combines different perspectives. Financial (cost), customer (satisfaction), internal (efficiency), learning (skills). Example: financial - reduce IT cost 10%, customer - 95% satisfaction, internal - response time < 5sec, learning - skills certification. CHALLENGES: (1) MEASUREMENT - complex systems, multiple metrics, (2) BASELINE - knowing what's good, (3) BUSINESS ALIGNMENT - IT may optimize wrong metrics, (4) TRADEOFFS - high availability costly, balance needed. REPORTING: management dashboards, monthly reviews, trend analysis. Performance management ensures IT delivers value, supports business outcomes. Understanding metrics critical for IT leadership.",
    category: "interview",
    subcategory: "deloitte",
    company: "Deloitte",
    topic: "IT Management"
  }
];

module.exports = deloitteQuestions;