// Seed data for Cognizant Interview Questions with Comprehensive Answers

const cognizantQuestions = [
  {
    question: "What is Microservices Architecture?",
    answer: "Microservices architecture breaks monolithic applications into small, independent services. Each service is a separate process running in its own container, handling specific business domain. KEY CHARACTERISTICS: (1) INDEPENDENT DEPLOYMENT - each service deployable independently without affecting others, (2) BOUNDED CONTEXTS - clear boundaries, each service manages own data, (3) TECHNOLOGY AGNOSTIC - different services can use different tech stacks, (4) RESILIENCE - failure of one service doesn't crash entire system, (5) SCALABILITY - scale individual services based on demand. Example: E-commerce application. Monolith: single application handling users, products, orders, payments. Microservices: UserService (authentication, profiles), ProductService (catalog, inventory), OrderService (order management), PaymentService (payment processing). Each has database, API, independent deployment. BENEFITS: (1) FLEXIBILITY - teams independently develop, test, deploy, (2) SCALABILITY - scale services independently, (3) RESILIENCE - fault isolation, circuit breakers, (4) TECHNOLOGY DIVERSITY - choose best tech per service, (5) CONTINUOUS DEPLOYMENT - smaller codebases, faster releases. CHALLENGES: (1) COMPLEXITY - distributed system complexity, debugging harder, (2) NETWORK LATENCY - inter-service communication slower than in-process, (3) DATA CONSISTENCY - managing transactions across services, (4) OPERATIONAL OVERHEAD - need monitoring, logging, tracing across services, (5) TESTING - integration testing more complex. Tools: Docker (containerization), Kubernetes (orchestration), ServiceMesh (Istio), monitoring (Prometheus, ELK). When to use: large teams, independent feature development, varied technology needs. When to avoid: small teams, simple applications, tight consistency requirements. Cognizant builds many microservices systems for enterprise clients.",
    category: "interview",
    subcategory: "cognizant",
    company: "Cognizant",
    topic: "Architecture"
  },
  {
    question: "Explain Cloud Computing Models (IaaS, PaaS, SaaS)?",
    answer: "Cloud Computing models define service delivery levels: responsibility distribution between provider and consumer. (1) INFRASTRUCTURE AS A SERVICE (IaaS): Provider manages infrastructure (servers, storage, networking). Consumer manages applications, data, runtime, middleware, OS. Example: AWS EC2, Microsoft Azure VMs, Google Cloud Compute. You rent computing resources, manage everything above. Cost: pay-per-use. Like renting land - you build/manage building. (2) PLATFORM AS A SERVICE (PaaS): Provider manages infrastructure, OS, middleware. Consumer manages applications and data. Example: Heroku, AWS Elastic Beanstalk, Google App Engine. Developers focus on code, not infrastructure. Like renting furnished office - just bring furniture (application). (3) SOFTWARE AS A SERVICE (SaaS): Provider manages everything. Consumer uses application via browser. Example: Salesforce, Microsoft 365, Google Workspace. No installation, just login and use. Like renting office space - everything managed. COMPARISON: (1) IaaS - most control, most responsibility, most cost (scalable), suitable for enterprises, (2) PaaS - balance, suitable for AppDev, (3) SaaS - least control, least responsibility, subscription-based. ADVANTAGES: (1) COST EFFICIENCY - no capital expenditure, operational expenditure, (2) SCALABILITY - pay for what you use, (3) RELIABILITY - redundancy, backup managed, (4) ACCESSIBILITY - access anywhere, (5) SECURITY - provider responsibility. DISADVANTAGES: (1) VENDOR LOCK-IN - difficult switching providers, (2) SECURITY CONCERNS - data on provider servers, (3) INTERNET DEPENDENCY - need reliable connectivity. Cognizant cloud migration services help enterprises transition to cloud models.",
    category: "interview",
    subcategory: "cognizant",
    company: "Cognizant",
    topic: "Cloud Computing"
  },
  {
    question: "What is DevOps and its practices?",
    answer: "DevOps (Development + Operations) culture bridging gap between development and operations teams, emphasizing automation, collaboration, integration. GOAL: faster, reliable software delivery with shorter development cycles. KEY PRACTICES: (1) CONTINUOUS INTEGRATION (CI) - developers integrate code multiple times daily, automated testing, quick feedback. Tools: Jenkins, GitLab CI. (2) CONTINUOUS DELIVERY (CD) - code always in deployable state, automated deployment to production. Ensures reliability, reduces manual errors. (3) INFRASTRUCTURE AS CODE (IaC) - define infrastructure (servers, networks) as code, version controlled, reproducible. Tools: Terraform, Ansible. (4) MONITORING & LOGGING - continuous monitoring application health, performance, logs centralized for analysis. Tools: Prometheus, ELK, Datadog. (5) CONTAINERIZATION - package applications with dependencies, ensures consistency across environments. Docker, Kubernetes. (6) AUTOMATION - automate testing (unit, integration, performance), deployment, infrastructure provisioning. Reduces manual work, human error. (7) COLLABORATION - developers, operations, QA work together from start. Shared ownership of code quality and reliability. BENEFITS: (1) FASTER RELEASES - automated pipelines reduce time to market, (2) RELIABILITY - automated testing catches issues early, (3) SCALABILITY - infrastructure code scales easily, (4) COST REDUCTION - less manual work, fewer production issues, (5) TEAM SATISFACTION - faster feedback, less blame culture. DEVOPS PIPELINE: Code -> Test -> Build -> Deploy -> Monitor -> Feedback. Continuous cycle. Example: developer commits code, CI/CD pipeline automatically tests, builds, deploys to staging, if passes, deploys to production, monitoring alerts on issues. TOOLS ECOSYSTEM: Git (version control), Jenkins (CI/CD), Docker (containerization), Kubernetes (orchestration), Terraform (IaC), Prometheus (monitoring). Cognizant DevOps services help enterprises implement continuous delivery.",
    category: "interview",
    subcategory: "cognizant",
    company: "Cognizant",
    topic: "DevOps"
  },
  {
    question: "Explain Design Patterns with examples?",
    answer: "Design Patterns reusable solutions to common programming problems, proven approaches solving recurring design challenges. THREE CATEGORIES: (1) CREATIONAL PATTERNS - focus on object creation mechanisms. (a) SINGLETON - ensures single instance of class, global access point. Example: Database connection pool, logger. Implementation: private constructor, static instance. (b) FACTORY - creates objects without specifying exact classes. Example: DocumentFactory creating PDF, Word documents. (c) BUILDER - constructs complex objects step-by-step. Example: StringBuilder, constructing user with many optional properties. (2) STRUCTURAL PATTERNS - deal with object composition, creating relationships. (a) ADAPTER - makes incompatible interfaces compatible. Example: USB adapter converting USB-C to USB-A. (b) DECORATOR - adds behavior to objects dynamically. Example: adding encryption to file handler. (c) FACADE - provides simplified interface to complex subsystems. Example: payment facade hiding credit card, PayPal complexity. (3) BEHAVIORAL PATTERNS - deal with communication between objects. (a) OBSERVER - multiple objects subscribe to state changes. Example: click events in UI, listeners notified. (b) STRATEGY - encapsulates algorithms interchangeably. Example: different sorting strategies (QuickSort, MergeSort). (c) COMMAND - encapsulates requests as objects. Example: undo/redo functionality. BENEFITS: (1) PROVEN SOLUTIONS - best practices, reduces bugs, (2) COMMUNICATION - patterns common language for architects, (3) CODE REUSE - patterns applicable across projects, (4) MAINTAINABILITY - familiar patterns easier to understand. ANTI-PATTERNS: common bad solutions causing issues. Example: God Object (class doing everything), Circular Dependencies. Good design doesn't force patterns unnecessarily (over-engineering), applies patterns where truly beneficial. Understanding patterns critical for senior developers, architectural decisions.",
    category: "interview",
    subcategory: "cognizant",
    company: "Cognizant",
    topic: "Design Patterns"
  },
  {
    question: "What is API Gateway and its role?",
    answer: "API Gateway single entry point for client requests in microservices architecture, sits between clients and microservices, handles cross-cutting concerns. ROLE: (1) REQUEST ROUTING - routes requests to appropriate microservices based on path, method, parameters. Example: /api/users routes to UserService, /api/products routes to ProductService. (2) LOAD BALANCING - distributes requests across multiple instances, prevents overload, ensures availability. (3) AUTHENTICATION & AUTHORIZATION - verifies client identity, checks permissions before forwarding. Centralized security. (4) RATE LIMITING - controls request rate, prevents abuse, protects backend services. (5) LOGGING & MONITORING - logs all requests, gathers metrics for analysis. (6) API VERSIONING - manages multiple API versions, gradual deprecation. (7) PROTOCOL TRANSLATION - converts between protocols (REST to gRPC), data formats. (8) CACHING - caches responses reducing backend load, improving performance. ADVANTAGES: (1) CENTRALIZED CONTROL - single point managing cross-cutting concerns, (2) SECURITY - authentication, rate limiting centralized, (3) SCALABILITY - backend services scale independently, (4) RESILIENCE - circuit breakers, timeouts, fallbacks, (5) FLEXIBILITY - change backend without client changes. DISADVANTAGES: (1) SINGLE POINT OF FAILURE - gateway failure affects all services, (2) LATENCY - additional hop adds latency, (3) COMPLEXITY - adds another component to maintain. POPULAR SOLUTIONS: (1) Nginx - lightweight, high-performance, (2) Kong - API management, rich features, (3) AWS API Gateway - fully managed, scalable, (4) Azure API Management - enterprise features. Implementation: define routes, authentication mechanisms, rate limits, caching policies. Crucial component enabling microservices architecture, handles complexity clients shouldn't know about.",
    category: "interview",
    subcategory: "cognizant",
    company: "Cognizant",
    topic: "API Design"
  },
  {
    question: "Explain AGILE Methodology and Scrum?",
    answer: "AGILE methodology emphasizes iterative development, customer collaboration, responding to change over rigid planning. Core values: (1) INDIVIDUALS & INTERACTIONS over processes & tools, (2) WORKING SOFTWARE over comprehensive documentation, (3) CUSTOMER COLLABORATION over contract negotiation, (4) RESPONDING TO CHANGE over following plan. SCRUM AGILE framework with defined roles, events, artifacts. ROLES: (1) PRODUCT OWNER - represents customer, maintains prioritized product backlog, accepts completed work, (2) SCRUM MASTER - facilitates process, removes impediments, coaches team, (3) DEVELOPMENT TEAM - self-organizing group delivering increments. EVENTS (Ceremonies): (1) SPRINT PLANNING - team selects items from backlog for upcoming sprint (2 weeks typical), defines tasks, estimates effort. (2) DAILY STANDUP - 15-min daily meeting, team discusses progress, blockers, plans day. (3) SPRINT REVIEW - team demonstrates completed work to stakeholders, gathers feedback. (4) SPRINT RETROSPECTIVE - team reflects on process, identifies improvements. ARTIFACTS: (1) PRODUCT BACKLOG - prioritized list of features, improvements, fixes. (2) SPRINT BACKLOG - items selected for current sprint, broken into tasks. (3) INCREMENT - working software produced each sprint. ADVANTAGES: (1) FLEXIBILITY - adapt to changing requirements, (2) EARLY DELIVERY - working software every sprint (2 weeks), (3) CUSTOMER INVOLVEMENT - continuous feedback, (4) QUALITY - regular review ensures quality, (5) TEAM SATISFACTION - clear goals, collaboration. CHALLENGES: (1) REQUIRES DISCIPLINE - daily standups, sprint ceremonies essential, (2) DOCUMENTATION - emphasis on software over docs, can be risky, (3) SCALING - hard scaling across multiple teams. Variants: Kanban (continuous flow, no fixed sprints), Scrumban (hybrid). Cognizant uses Agile extensively for project delivery, faster time-to-market.",
    category: "interview",
    subcategory: "cognizant",
    company: "Cognizant",
    topic: "Agile Methodology"
  }
];

module.exports = cognizantQuestions;
