// Seed data for Capgemini Interview Questions with Comprehensive Answers

const capgeminiQuestions = [
  {
    question: "What is Software Testing Life Cycle (STLC)?",
    answer: "Software Testing Life Cycle (STLC) defines systematic process for testing software application from beginning to end. Ensures quality, identifies defects early, validates functionality. PHASES: (1) REQUIREMENT ANALYSIS - understand requirements, identify testing objectives, feasibility analysis. Questions: What to test? What can't be tested? Risk areas? (2) TEST PLANNING - define test strategy, resources, timeline, test cases, tools. Prioritize testing efforts. (3) TEST DESIGN - design test cases, test scenarios based on requirements. Input-output combinations, edge cases, error conditions. (4) TEST ENVIRONMENT SETUP - configure test environment, install software, databases, tools. Match production as closely as possible. (5) TEST EXECUTION - run test cases, log results, identify failures. Compare actual vs expected results. (6) DEFECT REPORTING - document bugs with steps, severity, expected/actual behavior. Communicate with developers. (7) REGRESSION TESTING - retest after fixes ensuring no new issues introduced. (8) TEST CLOSURE - evaluate test coverage, document lessons learned, archive test artifacts. TEST TYPES: (1) UNIT TESTING - test individual components/functions, developer responsibility, white-box (code visible). (2) INTEGRATION TESTING - test component interactions, ensure data flow correct. (3) SYSTEM TESTING - test complete application, functional, performance, security testing. (4) USER ACCEPTANCE TESTING (UAT) - end-users test, verify functionality meets requirements. (5) PERFORMANCE TESTING - load, stress, endurance testing, identifies bottlenecks. (6) SECURITY TESTING - identifies vulnerabilities, penetration testing. APPROACH: (1) BLACK-BOX - test functionality without code visibility, typical QA, (2) WHITE-BOX - test code logic, paths, coverage, typical developers, (3) GRAY-BOX - combination, test documented interfaces with partial code visibility. TOOLS: Selenium (automation), Jira (tracking), Postman (API), JMeter (performance), Appium (mobile). BEST PRACTICES: (1) Test early, test often, (2) Test data diverse (valid, invalid, boundary), (3) Automate regression tests, (4) Clear test cases, (5) Defects tracked, categorized. Goal: quality software reaching production with minimum defects, user satisfaction.",
    category: "interview",
    subcategory: "capgemini",
    company: "Capgemini",
    topic: "Testing"
  },
  {
    question: "Explain Exception Handling in Java?",
    answer: "Exception Handling mechanism managing errors, preventing abrupt program termination. Allows graceful error recovery. EXCEPTION HIERARCHY: (1) THROWABLE (root) - extends Object, parent of Exception, Error. (2) EXCEPTION - checked exceptions, must catch/throw. Examples: IOException, SQLException. (3) RUNTIME EXCEPTION - unchecked, inherit from Exception. Examples: NullPointerException, ArithmeticException, IndexOutOfBoundsException. (4) ERROR - serious conditions, shouldn't catch. Examples: StackOverflowError, OutOfMemoryError. CHECKED vs UNCHECKED: (1) CHECKED - compiler enforces handling, must declare throws or catch, examples: IOException (file operations), SQLException (database). (2) UNCHECKED - compiler doesn't enforce, inherit RuntimeException, examples: NullPointerException (null reference), ArithmeticException (divide by zero). TRY-CATCH-FINALLY: try block contains code throwing exception. catch blocks handle specific exceptions, multiple catches for different exceptions. finally block executes regardless, cleanup resources. Example: TRY file reading CATCH IOException FINALLY close file. THROW: explicitly throw exception. Example: throw new IllegalArgumentException(\"Invalid input\"). THROWS: method declaration indicates exceptions thrown, caller must handle/propagate. Example: public void readFile() throws IOException {} CUSTOM EXCEPTIONS: extend Exception creating domain-specific exceptions. Example: InvalidUserException, AuthenticationException. BEST PRACTICES: (1) Catch specific exceptions, not generic Exception, (2) Log exceptions including stack trace, (3) Clean up resources (finally, try-with-resources), (4) Don't suppress exceptions silently, (5) Provide meaningful error messages, (6) Use custom exceptions for business logic. TRY-WITH-RESOURCES: automatically closes resources implementing AutoCloseable. Example: try(FileReader fr = new FileReader(\"file.txt\")) {} catches exceptions, closes file. EXCEPTION CHAINING: preserving original exception while throwing new one. Ex: catch(SQLException e) { throw new DAOException(\"DB error\", e); } Proper exception handling improves reliability, debugging, user experience.",
    category: "interview",
    subcategory: "capgemini",
    company: "Capgemini",
    topic: "Java"
  },
  {
    question: "What is Agile testing and Continuous Testing?",
    answer: "AGILE TESTING aligns testing with Agile development principles, continuous feedback, rapid iterations. CHARACTERISTICS: (1) COLLABORATIVE - testers, developers, customers work closely, (2) CONTINUOUS - testing happens throughout sprint, not separate phase, (3) ITERATIVE - sprint-by-sprint testing, quick feedback loops, (4) REGRESSION FOCUS - frequent changes require continuous regression testing, (5) AUTOMATION-HEAVY - automate repetitive tests enabling fast feedback, (6) CUSTOMER FOCUS - UAT integrated early. AGILE TEST LEVELS: (1) UNIT TESTING - developers test components, TDD (Test-Driven Development), (2) COMPONENT TESTING - components in isolation, (3) SYSTEM TESTING - complete application, (4) UAT - end-user validation. CONTINUOUS TESTING testing integrated into CI/CD pipeline, every code change tested immediately. BENEFITS: (1) EARLY DEFECT DETECTION - catch issues immediately, (2) FAST FEEDBACK - developers know status minimizing debugging, (3) AUTOMATION - frequent execution, manual impossible, (4) COST REDUCTION - early detection cheaper, (5) CONFIDENCE - constant quality assurance. CONTINUOUS TESTING PIPELINE: Code Commit -> Build -> Unit Tests -> Integration Tests -> System Tests -> Performance Tests -> Deploy. Automated at each stage. Tools: Jenkins (CI), Selenium (automation), JUnit (unit tests), SonarQube (code quality). TEST AUTOMATION PYRAMID: (1) UNIT TESTS (many, fast, cheap) - 60-70%, (2) INTEGRATION TESTS (medium, moderate) - 20-30%, (3) E2E TESTS (few, slow, expensive) - 5-10%. Inverted pyramid (too many E2E tests) is anti-pattern. AGILE TESTING METRICS: (1) Test Coverage - % code tested, (2) Defect Density - defects per 1000 lines of code, (3) Test Automation Ratio - % automated tests, (4) Mean Time To Fix (MTTF) - average defect fix time. CHALLENGES: (1) Testing speed - must keep pace with development, (2) Test data - need realistic data, (3) Tool selection - right automation framework, (4) Skill gap - testers need development knowledge. Capgemini implements Agile testing for enterprise projects ensuring quality in fast-paced environments.",
    category: "interview",
    subcategory: "capgemini",
    company: "Capgemini",
    topic: "Testing"
  },
  {
    question: "Explain Collections Framework in Java?",
    answer: "Collections Framework provides unified architecture representing, manipulating collections of objects. HIERARCHY: (1) COLLECTION (root interface) - add, remove, contains, size, isEmpty methods. (2) LIST - ordered collections, duplicates allowed, indexed access. Implementations: ArrayList (resizable array), LinkedList (linked nodes), Vector (synchronized). (3) SET - unordered collections, no duplicates. Implementations: HashSet (hash-based, unordered), TreeSet (sorted, Red-Black tree), LinkedHashSet (insertion order). (4) QUEUE - FIFO (First-In-First-Out), elements added rear, removed front. Implementations: PriorityQueue, LinkedList, Deque (double-ended). (5) MAP - key-value pairs, no duplicate keys. Implementations: HashMap (hash-based), TreeMap (sorted keys), LinkedHashMap (insertion order). LIST USE CASES: (1) ArrayList - random access frequent, modifications occur, preferred, (2) LinkedList - frequent additions/removals, poor random access. SET USE CASES: (1) HashSet - fast O(1) lookup, order unimportant, (2) TreeSet - sorted collections, O(log n) operations, (3) LinkedHashSet - maintain insertion order. MAP USE CASES: (1) HashMap - fast lookups O(1), unordered, (2) TreeMap - ordered by keys, sorted, (3) LinkedHashMap - insertion/access order. THREAD-SAFETY: (1) Non-synchronized - ArrayList, HashMap (fast, not thread-safe), (2) Synchronized - Collections.synchronizedList(), synchronizedMap() (thread-safe, slower), (3) Concurrent - ConcurrentHashMap, CopyOnWriteArrayList (thread-safe, optimized). ITERATORS: enhanced for-loop, Iterator interface for removal during iteration, ForEach streams (Java 8+). GENERICS: type-safe collections, compile-time type checking. Example: List<String> names = new ArrayList<>(); prevents ClassCastException. PERFORMANCE: ArrayList O(1) random access, O(n) insertion/removal. LinkedList O(n) random access, O(1) insertion/removal. HashMap O(1) average lookup, O(n) worst case. TreeMap O(log n) operations. STREAMS API (Java 8): functional operations on collections, filter, map, reduce. Example: list.stream().filter(s -> s.length() > 3).forEach(System.out::println). Collections choice important for performance, correctness, application requirements.",
    category: "interview",
    subcategory: "capgemini",
    company: "Capgemini",
    topic: "Java"
  },
  {
    question: "What is Data Abstraction and Encapsulation?",
    answer: "DATA ABSTRACTION hiding complex implementation details, exposing simple interface. Users interact with abstraction, not underlying complexity. Example: Database abstraction - developer uses connection.query() without knowing SQL execution details, network protocols, buffer management. BENEFITS: (1) SIMPLICITY - complex operations hidden, simple to use, (2) FLEXIBILITY - change implementation without affecting users, (3) LOOSE COUPLING - depends on interface, not implementation, (4) SECURITY - hide sensitive internals. ENCAPSULATION bundling data (variables) and methods into single unit (class), hiding internals from outside world. Achieved using access modifiers: (1) PRIVATE - accessible only within class, (2) PROTECTED - accessible within class, subclasses, same package, (3) PUBLIC - accessible everywhere, (4) PACKAGE-PRIVATE (default) - accessible within same package. Example: class Student { private String ssn; public setSSN(String ssn) { validate SSN; this.ssn = ssn; } } SSN private, only set through method with validation. Prevents direct invalid assignment. BENEFITS: (1) DATA HIDING - internal state protected, (2) VALIDATION - control modifications through setters, (3) FLEXIBILITY - change implementation, external code unaffected, (4) MAINTAINABILITY - easier to modify internals. GETTERS/SETTERS: provide controlled access, enable lazy initialization, caching, validation, triggers. Better than public fields. DIFFERENCE: Abstraction WHAT to hide (complexity), Encapsulation HOW to hide (within classes). Abstract class defines interface, Encapsulation implementation detail. EXAMPLE: Shape interface (abstraction) - area(), perimeter(). Circle extends Shape (encapsulation) - radius private, area() implemented. Users call area() without knowing calculation complexity. INFORMATION HIDING PRINCIPLE: expose minimum necessary, hide maximum possible. Examples: (1) Database classes hide query building, connection management, (2) Payment processors hide encryption, tokenization, (3) Collections frameworks hide internal data structures (ArrayList hides array resizing). Proper abstraction, encapsulation critical for maintainable, secure, flexible software systems.",
    category: "interview",
    subcategory: "capgemini",
    company: "Capgemini",
    topic: "OOP Concepts"
  },
  {
    question: "Explain Multithreading and Thread Synchronization?",
    answer: "MULTITHREADING multiple threads executing concurrently within single process, sharing resources, context switching. BENEFITS: (1) CONCURRENCY - multiple tasks simultaneously, (2) RESPONSIVENESS - UI responsive while background operations occur, (3) RESOURCE SHARING - threads share heap memory, (4) EFFICIENCY - better CPU utilization. THREAD CREATION: (1) EXTEND Thread class - override run() method, (2) IMPLEMENT Runnable - implement run() method, passed to Thread. Runnable preferred (inheritance single). THREAD LIFECYCLE: (1) NEW - thread created, not started, (2) RUNNABLE - started, eligible running, waiting CPU, (3) RUNNING - currently executing, (4) BLOCKED - waits resource (lock, I/O), (5) DEAD - finished, terminated. THREAD SYNCHRONIZATION: multithreading introduces race conditions (multiple threads modifying shared data). Synchronization ensures mutual exclusion, data consistency. (1) SYNCHRONIZED KEYWORD - method/block acquiring lock on object, only one thread executes at time. Example: synchronized void incrementCounter() {} (2) VOLATILE - ensures visibility across threads, updates immediately visible. (3) LOCKS - ReentrantLock more flexible than synchronized, fairness, try-lock. (4) ATOMIC CLASSES - AtomicInteger, AtomicBoolean, thread-safe without synchronization. (5) IMMUTABILITY - immutable objects thread-safe naturally. THREAD COMMUNICATION: (1) WAIT/NOTIFY - thread waits condition, another notifies. wait() releases lock, notify() wakes one thread. (2) BLOCKING QUEUES - thread-safe exchange data. DEADLOCK: circular wait, threads indefinitely blocked. Prevention: lock ordering, timeouts, deadlock detection. BEST PRACTICES: (1) Minimize lock scope - synchronize only critical sections, (2) Use concurrent collections - ConcurrentHashMap instead of synchronized, (3) Avoid nested locks - deadlock risk, (4) Thread pools - ExecutorService managing threads, (5) Future/Callable - get results from threaded tasks. Example: ExecutorService executor = Executors.newFixedThreadPool(10); Future result = executor.submit(callable); result.get(). CHALLENGES: debugging difficult (race conditions intermittent), performance (context switching overhead), complexity. Multithreading essential for modern applications, requires careful design to avoid issues.",
    category: "interview",
    subcategory: "capgemini",
    company: "Capgemini",
    topic: "Concurrency"
  }
];

module.exports = capgeminiQuestions;
