// Seed data for Accenture Interview Questions with Comprehensive Answers

const accentureQuestions = [
  {
    question: "Explain Code Optimization Techniques?",
    answer: "Code Optimization improves performance, reduces memory usage, energy consumption. Techniques: (1) ALGORITHMIC OPTIMIZATION - choose better algorithm. O(n²) to O(n) has dramatic impact. Example: linear search O(n) to binary search O(log n). (2) LOOP OPTIMIZATION - reduce iterations, avoid expensive operations inside loops. Example: Computing array length outside loop vs inside. (3) MEMORY OPTIMIZATION - reduce memory footprint, efficient data structures. Use arrays instead of linked lists if random access frequent. (4) CACHING - store computed values, avoid recomputation. Memoization in recursive functions. (5) LAZY EVALUATION - compute only when needed, defer expensive operations. (6) PARALLELIZATION - use multi-threading/multi-processing for parallel operations. (7) CODE REFACTORING - eliminate duplication, simplify complexity. (8) COMPILER OPTIMIZATION - inline functions, dead code elimination. (9) PROFILING - identify bottlenecks with tools (JProfiler, YourKit), optimize what matters. Premature optimization antipattern (optimize before profiling). PROCESS: (1) PROFILE - measure current performance, identify hotspots, (2) OPTIMIZE - target bottlenecks with appropriate techniques, (3) BENCHMARK - compare before/after, (4) VERIFY - ensure correctness maintained. Example: web request handler profiling shows 80% time in database query, optimize query (index, caching), not in request parsing. Trade-offs: optimization often trades simplicity for speed, memory for speed. Balance: optimized code complex, maintainability suffers. Profile first, optimize judiciously, maintain readability. Understanding optimization crucial for performance-critical systems.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "Performance"
  },
  {
    question: "What is API Rate Limiting?",
    answer: "Rate Limiting controls request volume to API, protecting from abuse, ensuring fair use. CONCEPT: limit requests per time period per client. Example: 1000 requests/hour per API key. PURPOSE: (1) SECURITY - prevent brute force attacks, DoS attacks, (2) FAIR USE - ensure no user monopolizes resources, (3) COST CONTROL - usage-based pricing, (4) STABILITY - prevent overload, (5) BUSINESS POLICY - enforce tier-based access (free tier limits). ALGORITHMS: (1) FIXED WINDOW - divide time into buckets, count requests per bucket. Example: hourly buckets, 1000/hour. Simple but edge cases (burst at boundaries). (2) SLIDING WINDOW - more accurate, overhead tracking individual requests. (3) TOKEN BUCKET - tokens replenish at rate, spend token per request, burstable. Allows controlled bursts. (4) LEAKY BUCKET - requests queue, process at constant rate, bursty traffic smoothed. IMPLEMENTATION: (1) CLIENT-SIDE - respectful client limits requests, honor server headers, (2) SERVER-SIDE - server enforces limits, returns 429 Too Many Requests. HTTP headers: X-RateLimit-Limit (max), X-RateLimit-Remaining (remaining), X-RateLimit-Reset (reset time). STRATEGIES: (1) PER USER - limit per authenticated user, (2) PER IP - limit per IP address (anonymous), (3) PER ENDPOINT - different limits for different endpoints, (4) TIERED - different limits for different user tiers IMPLEMENTATION in code: use libraries (Spring Rate Limiter), Redis (distributed), API gateway (AWS API Gateway). Example: GitHub API 60 requests/hour unauthenticated, 5000 authenticated. Handling: inform client clearly (headers), provide way to increase (payment), queue requests gracefully. Understanding rate limiting essential for API design.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "API Design"
  },
  {
    question: "Explain Business Analysis in IT Projects?",
    answer: "Business Analysis bridges business needs and technical solutions. ROLE OF BUSINESS ANALYST: (1) REQUIREMENTS GATHERING - interview stakeholders, understand business problems, document needs. Example: company wants faster reporting. Why? Users wait 30 minutes. Impact: reduced productivity. (2) REQUIREMENTS ANALYSIS - translate business needs to technical requirements. Non-functional requirements: performance 30sec report, scalability 1000 concurrent. (3) SOLUTION DESIGN - work with architects, propose solutions. Rewrite existing system or add caching? (4) STAKEHOLDER MANAGEMENT - communicate progress, manage expectations, handle changes. (5) DOCUMENTATION - create specifications, use cases, user stories. (6) TESTING - define test cases, acceptance criteria. PROCESS: (1) DISCOVERY - understand current state, problems, opportunities. (2) ANALYSIS - analyze requirements, prioritize, dependencies. (3) DESIGN - propose solutions, trade-off analysis, ROI. (4) IMPLEMENTATION - work with dev team, ensure build matches requirements. (5) VALIDATION - test meets requirements, user acceptance, (6) DEPLOYMENT - transition to production, training. TECHNIQUES: (1) INTERVIEWS - one-on-one stakeholder conversations, (2) WORKSHOPS - group discussions, brainstorming, (3) USE CASES - detail scenarios, (4) USER STORIES - 'as user, I want, so that', (5) PROCESS MAPPING - visualize workflows, (6) COMPETITOR ANALYSIS - learn from industry. CHALLENGES: (1) SCOPE CREEP - requirements keep growing, (2) CHANGING REQUIREMENTS - business changes during project, (3) COMMUNICATION - technical/non-technical gap, (4) HIDDEN REQUIREMENTS - stakeholders don't articulate all needs until late. SUCCESS: Business Analyst balances business goals, technical feasibility, user experience, delivering value. Understanding BA role crucial for project success.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "Project Management"
  },
  {
    question: "What is Digital Transformation?",
    answer: "Digital Transformation is large-scale adoption of technology to fundamentally change business operations, culture, strategy. ASPECTS: (1) PROCESS TRANSFORMATION - digitize manual processes. Example: paper forms to online portals, approvals automated via workflow. (2) CUSTOMER EXPERIENCE - digital channels, personalization. Online shopping replacing manual store visits, chatbots replacing phone support. (3) BUSINESS MODEL INNOVATION - create new revenue streams. Uber (ride-sharing), Netflix (streaming) transformed industries. (4) DATA & ANALYTICS - leverage data for decisions. IoT sensors monitoring manufacturing, ML predicting maintenance. (5) ORGANIZATIONAL CULTURE - embrace technology, continuous learning, agility. DRIVERS: (1) CUSTOMER EXPECTATIONS - digital-native users expect digital services, (2) COMPETITION - disruptive startups, legacy companies adapt or perish, (3) EFFICIENCY - automation reduces costs, (4) INNOVATION - new tech enables new possibilities, (5) REVENUE - create new business opportunities. CHALLENGES: (1) LEGACY SYSTEMS - complex integration, (2) SKILLS GAP - employees need retraining, (3) CULTURE RESISTANCE - change management difficult, (4) INVESTMENT - significant capital, uncertain ROI, (5) SECURITY - increased digital exposure. EXAMPLES: (1) RETAIL - physical stores to e-commerce, digital payments, (2) BANKING - branch-based to mobile banking, (3) MANUFACTURING - manual to automated, IoT monitoring, (4) HEALTHCARE - paper records to EHR, telemedicine. TIMELINE: typically 3-5 years, ongoing. SUCCESS FACTORS: executive sponsorship, clear vision, phased approach, continuous improvement. Digital transformation no longer optional but essential for business survival. Understanding transformation critical for consulting roles.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "Business"
  },
  {
    question: "Explain Database Optimization?",
    answer: "Database Optimization improves query performance, reduces resource usage. TECHNIQUES: (1) INDEXING - covered previously, enables fast lookups. (2) QUERY OPTIMIZATION - rewrite inefficient queries. Example: avoid SELECT *, specify needed columns. Use JOIN efficiently, avoid Cartesian product. (3) DENORMALIZATION - selectively break normalization for performance. Example: store frequently accessed aggregates instead of computing. Trade-off: storage vs speed. (4) PARTITIONING - split large tables by range (date), hash (id). Improves query performance, parallel processing. Example: sales table by year. (5) ARCHIVING - move old data off live database. Example: archive 5+ year old records. (6) STATISTICS - DBMS uses to choose optimal query plan. Keep statistics updated. (7) CONFIGURATION TUNING - memory allocation, cache size, connection pooling. (8) HARDWARE - faster storage, more RAM, better CPU. (9) CONNECTION POOLING - reuse connections, avoid overhead. (10) QUERY BATCHING - execute many queries together more efficient. ANALYSIS: (1) EXPLAIN PLAN - show query execution plan, identify inefficiencies. (2) SLOW QUERY LOG - log queries exceeding threshold, (3) MONITORING - track resource usage, identify bottlenecks. TRADE-OFFS: optimization often trades consistency for speed (caching stale), simplicity for complexity, storage for speed. PROCESS: (1) IDENTIFY - profile, log slow queries, (2) ANALYZE - understand bottleneck, (3) OPTIMIZE - apply techniques, (4) BENCHMARK - measure improvement, (5) MONITOR - track ongoing. Example: application slow. EXPLAIN PLAN shows full table scan. Add index, query 100x faster. Understanding database optimization critical for large-scale systems.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "Database"
  },
  {
    question: "What is Enterprise Architecture?",
    answer: "Enterprise Architecture holistically plans organization's IT systems, aligns with business strategy. SCOPE: IT infrastructure, applications, data, processes, security, across entire organization. FRAMEWORKS: (1) ZACHMAN FRAMEWORK - matrix of 6 communication questions (who, what, where, when, why, how) and 6 levels (scope, business, system, tech, detailed, operational). Comprehensive but complex. (2) TOGAF (The Open Group Architecture Framework) - industry standard, ADM (Architecture Development Method) provides process. Phases: preliminary, vision, business, information systems, tech, opportunities, implementation, governance. (3) FEA (Federal EA) - US government framework, process-oriented. (4) MODAF (UK MOD) - military focused. BENEFITS: (1) ALIGNMENT - IT strategy matches business goals, (2) EFFICIENCY - eliminate redundancy, (3) SCALABILITY - design for growth, (4) FLEXIBILITY - adapt to changes, (5) RISK MANAGEMENT - identify issues early, (6) COST OPTIMIZATION - avoid duplicate systems. COMPONENTS: (1) BUSINESS ARCHITECTURE - business strategy, processes, capabilities. (2) DATA ARCHITECTURE - data structures, flows, governance. (3) APPLICATION ARCHITECTURE - applications, interfaces, integration. (4) TECH ARCHITECTURE - infrastructure, platforms, standards. (5) SECURITY ARCHITECTURE - security policies, controls. (6) GOVERNANCE - decision-making, controls, compliance. CHALLENGES: (1) SCOPE - large organizations overwhelming, (2) TIME - lengthy process, (3) CHANGE - rapid tech evolution, (4) RESISTANCE - culture change needed, (5) SKILLS - expertise required. MATURITY MODEL helps assess organization EA capability. Large enterprises (banks, airlines) heavily invest in EA for strategic alignment. Understanding EA crucial for strategic IT decisions.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "Architecture"
  },
  {
    question: "Explain Data Governance?",
    answer: "Data Governance establishes policies, procedures, controls for data management, quality, security, compliance. OBJECTIVES: (1) DATA QUALITY - accurate, consistent, complete, (2) SECURITY - protect from unauthorized access, (3) COMPLIANCE - meet regulations (GDPR, HIPAA, PCI), (4) INTEGRITY - maintain correctness, prevent corruption, (5) AVAILABILITY - accessible when needed, (6) TRACEABILITY - know data origin, changes. COMPONENTS: (1) POLICIES - rules for data handling, access, retention. Example: data deleted after 7 years. (2) STEWARDSHIP - assign responsibility. Data stewards own data quality. (3) METADATA MANAGEMENT - document data (definitions, sources, lineage). (4) QUALITY MANAGEMENT - validate, cleanse, standards. (5) SECURITY - encryption, access controls, audit. (6) COMPLIANCE - GDPR (right to be forgotten), HIPAA (patient data), CCPA, SOC 2. (7) ARCHITECTURE - systems supporting governance. STAKEHOLDERS: (1) DATA STEWARDS - responsible for data domains, quality. Example: customer data steward ensures customer master data quality. (2) DATA OFFICERS - executive oversight. (3) IT/TECH - implement systems, security. (4) BUSINESS - owners of business processes. CHALLENGES: (1) CULTURAL - resistance to governance overhead, (2) TECHNICAL - legacy systems, (3) ORGANIZATIONAL - finding right structure, (4) COST - implementation investment, (5) COMPLEXITY - large organizations vast data. IMPLEMENTATION: (1) ASSESS - current state, issues, (2) DESIGN - governance model, policies, (3) BUILD - tools, processes, (4) DEPLOY - rollout, training, (5) MONITOR - track effectiveness, continuous improvement. BENEFITS: (1) TRUST - knowledge data reliable, (2) RISK REDUCTION - compliance, security, (3) IMPROVED DECISIONS - quality data, (4) EFFICIENCY - eliminate redundancy. Data governance critical in data-driven organizations, GDPR enforcement.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "Data Management"
  },
  {
    question: "What is Change Management in IT?",
    answer: "Change Management controls introduction of changes minimizing disruption, risks. IT changes: new software deployment, infrastructure updates, process changes. PROCESS: (1) REQUEST - document change, reason, impact, (2) PLANNING - what, when, rollback plan, (3) APPROVAL - CAB (Change Advisory Board) review, (4) TESTING - validate in test environment, (5) COMMUNICATION - notify affected stakeholders, (6) DEPLOYMENT - execute according to plan, (7) VERIFICATION - confirm success, (8) ROLLBACK - if issues, revert to previous state. TYPES: (1) NORMAL CHANGES - routine, low risk, standard process. (2) EMERGENCY CHANGES - urgent, critical issues, expedited approval. (3) STANDARD CHANGES - pre-approved repetitive changes, streamlined process. BENEFITS: (1) RISK REDUCTION - identify issues before production, (2) STABILITY - minimize outages, (3) VISIBILITY - everyone informed, (4) ACCOUNTABILITY - track who did what, when, (5) REVERSIBILITY - rollback plans. CHALLENGES: (1) OVERHEAD - process can slow things, (2) CULTURE - developers resist process, (3) COMMUNICATION - keep everyone updated, (4) TESTING - adequate testing critical. METRICS: (1) SUCCESS RATE - % changes without issues, (2) ROLLBACK RATE - % requiring rollback, (3) TIME TO DEPLOY - deployment time, (4) MEAN TIME BETWEEN FAILURES - stability metric. TOOLS: ServiceNow, Jira, Atlassian. ORGANIZATIONAL CHANGE: separate from technical change management. Addresses people side, training, communication, adoption. Both technical and organizational change management needed for successful transformation. Understanding change management critical for controlled systems.",
    category: "interview",
    subcategory: "accenture",
    company: "Accenture",
    topic: "IT Service Management"
  }
];

module.exports = accentureQuestions;