// Seed data for Wipro Interview Questions with Comprehensive Answers

const wiproQuestions = [
  {
    question: "Explain Software Testing Types?",
    answer: "Software Testing verifies application works as intended. UNIT TESTING: tests individual components/functions in isolation. Example: test addition function returns correct sum. Written by developers. Tools: JUnit, NUnit, pytest. Fast, cheap, isolated (doesn't catch integration issues). INTEGRATION TESTING: tests interaction between components/modules. Example: database module with API module together. Finds issues in interfaces between modules. Tools: TestNG. More complex than unit. SYSTEM TESTING: tests entire system end-to-end. Example: complete application flow from login to purchase. Verifies system meets requirements. Tools: Selenium. ACCEPTANCE TESTING: validates system meets business requirements, user acceptance criteria. User/customer performs. Black-box testing (no code knowledge). Example: does system have all promised features? REGRESSION TESTING: ensures changes don't break existing functionality. When new feature added or bug fixed, run all previous tests. Prevents reintroduction of old bugs. SMOKE TESTING: quick tests on critical functionality. Determines if build stable enough for further testing. SANITY TESTING: limited testing on specific functionality. PERFORMANCE TESTING: load testing (how many users supported), stress testing (maximum load), spike testing (sudden load increase). Example: application with 10000 concurrent users performs? SECURITY TESTING: vulnerability, penetration testing, authentication, authorization. Example: can unauthorized user access admin panel? Testing pyramid: many unit tests (fast, cheap), fewer integration tests, minimal system tests. Automation: unit/integration automated (continuous), system/manual less so (expensive). Understanding testing types ensures robust applications.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "Testing"
  },
  {
    question: "What is Scalability and its types?",
    answer: "Scalability is system's ability to handle growing load (users, data, transactions) maintaining performance. TWO TYPES: (1) VERTICAL SCALING (Scale-Up): increase server resources (CPU, RAM, storage). Upgrade single machine to better hardware. Example: 8GB to 16GB RAM. Simple, limited by hardware maximum, single point of failure, downtime needed. (2) HORIZONTAL SCALING (Scale-Out): add more servers/machines. Distribute load across multiple machines. Example: 1 server to 10 servers. No limits, eliminates single point of failure, more complex (load balancing, distributed databases), cost-effective. Cloud prefers horizontal scaling. Implementation approaches: (1) LOAD BALANCING - distribute traffic across servers (round-robin, least connections), (2) CACHING - reduce database requests (Redis, Memcached), (3) DATABASE REPLICATION - distribute data reads across replicas, (4) MICROSERVICES - independent scaling of services, (5) ASYNCHRONOUS PROCESSING - queues for async tasks, (6) DATABASE PARTITIONING (sharding) - distribute data across databases. Measuring: (1) LATENCY - response time, (2) THROUGHPUT - requests per second, (3) AVAILABILITY - uptime percentage. Example: Netflix uses horizontal scaling, micro-services, caching handling millions of concurrent users. Choosing: consider cost (vertical simpler but expensive), application design (stateless easier horizontal), growth trajectory. Understanding scalability crucial for system design.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "System Design"
  },
  {
    question: "Explain Agile Sprint Cycle?",
    answer: "Agile Sprint is time-boxed iteration (typically 1-4 weeks, usually 2 weeks) delivering potentially shippable increment. SPRINT CYCLE: (1) SPRINT PLANNING: team meets, product owner presents prioritized features from backlog, team estimates effort (story points), commits to sprint goal. Example: 'Implement user login with email/password'. (2) DAILY STANDUP: 15-min daily meeting each team member answers: what did I complete, what will I do today, any blockers? Keeps team synced, identifies issues early. (3) DEVELOPMENT: team works on committed tasks, self-organizes daily. Uses Kanban board (To Do, In Progress, Done) visualizing workflow. (4) TESTING: continuous testing throughout sprint, not at end. (5) SPRINT REVIEW: end of sprint, team demonstrates working software to stakeholders/product owner. Gather feedback. (6) RETROSPECTIVE: team reflects, what went well, what to improve, action items for next sprint. Continuous improvement culture. Benefits: (1) PREDICTABILITY - regular delivery cadence, (2) FEEDBACK - frequent stakeholder input, (3) ADAPTABILITY - adjust priorities between sprints, (4) VISIBILITY - progress clear to all, (5) MOTIVATION - tangible completion every sprint. Metrics: VELOCITY - story points completed per sprint, tracks productivity, aids planning. BURNDOWN CHART - remaining work over sprint days, if below trend line, on schedule. Sprint success: team delivers committed scope, code quality maintained, team morale positive. Understanding sprint cycle essential for Agile implementation.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "SDLC"
  },
  {
    question: "What is HTTP Status Codes?",
    answer: "HTTP Status Codes indicate request outcome in three digits. CATEGORIES: (1) 1xx (Informational): request received, processing continues, rarely seen in practice. (2) 2xx (Success): request succeeded. 200 OK (general success), 201 Created (new resource), 204 No Content (success no body), 206 Partial Content (range request). (3) 3xx (Redirection): request needs action to complete. 301 Moved Permanently (old URL, use new), 302 Found (temporary redirect), 304 Not Modified (cached version valid). (4) 4xx (Client Error): invalid request, client responsibility. 400 Bad Request (malformed), 401 Unauthorized (auth needed), 403 Forbidden (auth exists, no permission), 404 Not Found (resource missing), 409 Conflict (request conflicts with state), 429 Too Many Requests (rate limited). (5) 5xx (Server Error): server failed handling valid request. 500 Internal Server Error (generic), 503 Service Unavailable (temporary). Choosing correct codes: indicate intent clearly, enables client proper handling (retry 503, don't retry 401). Example: user registers: 201 Created (new user resource), update profile: 204 No Content (updated, no return), missing endpoint: 404 Not Found, invalid input: 400 Bad Request, no permission: 403 Forbidden. REST best practice: use appropriate codes. Tools like Postman, curl show codes. Monitoring: track code distribution, high 4xx/5xx indicates issues. Understanding codes crucial for API design, client implementation.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "HTTP"
  },
  {
    question: "Explain Singleton Pattern use cases?",
    answer: "Singleton Pattern ensures class has only one instance globally. USE CASES: (1) LOGGING - single logger instance across application, consistent log file. (2) DATABASE CONNECTION - single connection pool manages all database operations, efficient resource usage. (3) CONFIGURATION - single config object loaded at startup, shared everywhere. (4) CACHING - single cache instance, centralized data storage. (5) THREAD POOL EXECUTOR - single executor managing worker threads. (6) FILE HANDLER - single file manager preventing multiple processes writing same file. (7) API CLIENT - single client instance reusing connections. BENEFITS: (1) GLOBAL ACCESS - everywhere needs instance via getInstance(), (2) LAZY INITIALIZATION - instance created when first needed, (3) THREAD-SAFE - controls instantiation, no duplicates, (4) RESOURCE EFFICIENT - avoid multiple expensive objects. IMPLEMENTATION: (1) EAGER - instance created at class load, guaranteed thread-safe, wastes memory if unused, (2) LAZY - instance on first use, memory efficient, complex thread-safety, (3) DOUBLE-CHECKED LOCKING - reduces locking overhead, complex, (4) ENUM - simplest thread-safe, serialization-proof Java approach, (5) STATIC HOLDER - combines lazy + thread-safe elegantly. DOWNSIDES: (1) GLOBAL STATE - harder to test (dependency injection preferred), (2) TIGHT COUPLING - code depends on singleton, not abstraction, (3) CONCURRENCY - multi-threading complexity. MODERN PERSPECTIVE: overuse singleton antipattern. Prefer dependency injection (Spring IoC manages instances). Singleton still valid for logging, configuration. Understanding when to use crucial, avoiding overuse prevents poor design.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "Design Patterns"
  },
  {
    question: "What is Cloud Deployment Models?",
    answer: "Cloud Deployment Models determine where cloud services hosted and who manages infrastructure. PUBLIC CLOUD: infrastructure owned/operated by cloud provider (AWS, Azure, GCP), accessible internet, shared resources among customers, multi-tenant. Advantages: cost-effective (shared), scalable, reliable, global availability. Disadvantages: less control, privacy concerns, potential noisy neighbor issues (one customer heavy load affects others). Suitable: startups, non-sensitive data, public applications. PRIVATE CLOUD: infrastructure dedicated to organization, managed on-premises or by provider. Single-tenant, complete control. Advantages: security, compliance, control, customization. Disadvantages: expensive (dedicated), less scalable economically, requires IT expertise. Suitable: enterprises, sensitive data (healthcare, finance), legacy systems. HYBRID CLOUD: mix public and private clouds, workloads shift between. Example: sensitive data on private, public-facing website on public. Advantages: flexibility, optimization (cost, security), disaster recovery. Disadvantages: complexity, management overhead. Suitable: enterprises with mixed requirements. COMMUNITY CLOUD: shared by specific organizations with common interests (government, industry). Example: healthcare cloud for medical organizations. Advantages: focus on specific needs, shared cost. Disadvantages: limited providers, specific requirements. Choosing requires analyzing: data sensitivity, compliance requirements, cost, performance, scalability needs. Trend: hybrid/multi-cloud strategies gaining adoption (avoid lock-in, optimize cost). Understanding models crucial for infrastructure decisions.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "Cloud"
  },
  {
    question: "Explain Clean Code principles?",
    answer: "Clean Code is readable, maintainable, elegant code following best practices. PRINCIPLES: (1) MEANINGFUL NAMES: use clear, intention-revealing names. 'user' instead of 'u', 'getUserByEmail' instead of 'get'. Search-friendly, self-documenting. (2) FUNCTIONS: small, do one thing, one reason to change. Hard to test large functions. Maximum 20 lines. (3) DRY (Don't Repeat Yourself): avoid duplication, extract repeated logic to functions. Duplication breeds bugs. (4) ERROR HANDLING: handle errors explicitly, don't ignore. Use exceptions properly, catch specific types, provide context. (5) FORMATTING: consistent indentation, line length < 120 chars, related code grouped, visual structure. (6) COMMENTS: minimal, explain 'why' not 'what' (code shows what). Comments often outdated. Example: good function self-explanatory, comments unnecessary. (7) TESTING: write tests, unit tests especially. Code written with testing in mind is cleaner. (8) CHECK FOR BAD CODE SMELLS: long methods, duplicate code, complex conditionals, feature envy (class using many methods of another class). Each smell indicates refactoring opportunity. (9) USE DESIGN PATTERNS: proven solutions to common problems, don't reinvent. (10) SIMPLICITY: simplest solution is often best, avoid over-engineering. Benefits: readability (team understands), fewer bugs (less complexity), easier maintenance, sustainable velocity. Books: 'Clean Code' by Robert Martin, 'Code Complete' by Steve McConnell. Tools: linters (detect issues), code reviews (enforce), refactoring. Understanding clean code principles essential for professional development.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "Best Practices"
  },
  {
    question: "What is Continuous Integration/Deployment (CI/CD)?",
    answer: "CI/CD automates software delivery from code changes to production. CONTINUOUS INTEGRATION (CI): developers merge code changes frequently, each commit triggers automated build and tests. Catches integration issues early. Advantages: early error detection, reduced integration time, faster feedback. Tools: Jenkins, GitLab CI, GitHub Actions. Flow: developer commits code -> CI pipeline triggered -> code compiled -> unit tests run -> integration tests run -> if pass, artifact created, if fail, developer notified. CONTINUOUS DEPLOYMENT (CD): automatically deploy tested code to production. Every merged code automatically goes to production (not manual). CONTINUOUS DELIVERY: code ready for production anytime but deployed manually. Difference: CD fully automated, CD requires approval. BENEFITS: (1) FASTER DELIVERY - features to users quickly, (2) QUALITY - automated testing catches bugs, (3) REDUCED MANUAL WORK - less error-prone, (4) FEEDBACK - users provide feedback faster, (5) REDUCE RISK - smaller changes less risky. CHALLENGES: (1) INFRASTRUCTURE - complex setup, (2) TESTING COVERAGE - must have comprehensive tests, (3) ORGANIZATIONAL - culture change needed, (4) DATABASE - schema changes tricky. Pipeline stages: (1) Source - code trigger, (2) Build - compile, (3) Test - unit/integration, (4) Package - artifact creation, (5) Deploy staging - test environment, (6) Deploy production - live. Metrics: deployment frequency, lead time, mean time to recovery, change failure rate. Industry trend: critical for fast-moving companies (Netflix, Amazon), enables rapid iteration. Understanding CI/CD essential for modern software development.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "DevOps"
  },
  {
    question: "Explain Tokenization for Security?",
    answer: "Tokenization replaces sensitive data with non-sensitive token. CONCEPT: instead of storing/transmitting sensitive data (credit card, password), store/use token referencing actual data. Example: payment system, instead of API seeing card number, receives token. (1) USER SUBMITS CARD - (2) TOKENIZER generates unique token - (3) MAPPING STORED (token -> card number) - (4) TOKEN RETURNED - (5) API USES TOKEN, never sees card. Benefits: (1) SECURITY - sensitive data never exposed to application, (2) COMPLIANCE - easier PCI DSS (payment card security standard) compliance, (3) THEFT RESISTANCE - token useless without mapping, (4) FLEXIBILITY - swap sensitive data without changing application. TYPES: (1) RANDOM TOKENIZATION - generate random string, fast, no pattern, (2) FORMAT-PRESERVING TOKENIZATION - token same format as original (16-digit token for 16-digit card), maintains processes, (3) DETERMINISTIC - same input always produces same token, enables consistency. MECHANISMS: (1) VAULT - store mapping server-side, database lookup, (2) STATELESS - encode original in token (less secure but stateless), (3) HYBRID - combine approaches. APPLICATIONS: (1) PAYMENT CARDS - payment gateways tokenize cards, (2) SSN/IDs - replace with tokens in logs, (3) HEALTHCARE - patient data tokenization. LIMITATIONS: if tokenization server compromised, mapping exposed. Security depends on vault security. Industry standard for sensitive data handling. Understanding tokenization essential for compliance, security.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "Security"
  },
  {
    question: "What is Load Testing and its Tools?",
    answer: "Load Testing simulates expected production load on application, measures behavior, identifies bottlenecks. OBJECTIVES: (1) DETERMINE PERFORMANCE - response times under load, (2) FIND BOTTLENECKS - database, network, memory, (3) VALIDATE CAPACITY - handle expected users, (4) STRESS TEST - find breaking point, (5) BASELINE - establish performance norms. PROCESS: (1) DEFINE LOAD - expected concurrent users, transactions, (2) CREATE SCENARIOS - realistic user workflows, (3) EXECUTE TESTS - gradually increase load, monitor, (4) ANALYZE RESULTS - identify issues, causes, (5) REPORT - document findings, recommendations. TYPES: (1) LOAD TESTING - normal expected load, (2) STRESS TESTING - exceed normal to breaking point, (3) SPIKE TESTING - sudden load increase, (4) SOAK TESTING - sustained load over time, detect memory leaks. METRICS: (1) RESPONSE TIME - how long request takes, (2) THROUGHPUT - requests per second, (3) ERROR RATE - failed requests percentage, (4) CPU/MEMORY - resource consumption, (5) DATABASE - query times, connection pool. TOOLS: (1) JMeter - open-source, HTTP protocols, record scripts, easy,  (2) LoadRunner - commercial, comprehensive, (3) Gatling - Scala-based, real-time reporting, (4) Locust - Python, flexible, (5) k6 - modern, cloud-native, (6) Apache Bench - simple, command-line. Example: e-commerce site should handle 10000 concurrent users, load test simulates, measures response times, error rates. If response time > acceptable, fix identified bottleneck (database optimization, caching, scaling). Load testing essential before production launch.",
    category: "interview",
    subcategory: "wipro",
    company: "Wipro",
    topic: "Testing"
  }
];

module.exports = wiproQuestions;